name: Publish Retype Docs
on:
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Build website
        uses: retypeapp/action-build@latest

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.retype' # <-- Fixed path mapping

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
